/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#include "XC_CoreClasses.h"

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName XC_IPDRV_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class UXC_IpDrvStatics : public UXC_CoreStatics
{
public:
    DECLARE_CLASS(UXC_IpDrvStatics,UXC_CoreStatics,CLASS_Abstract,XC_IpDrv)
	NO_DEFAULT_CONSTRUCTOR(UXC_IpDrvStatics);
};

#endif

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if _MSC_VER
#pragma pack (pop)
#endif

